services:
  oracle-db:
    image: gvenzl/oracle-xe:21.3.0-slim
    container_name: oracle-plsql
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      APP_USER: ${APP_USER}
      APP_USER_PASSWORD: ${APP_USER_PASSWORD}
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data: